FROM ghcr.io/coder/code-server:latest

USER root

RUN apt-get update \
    && apt-get install --yes --no-install-recommends \
        bash-completion \
        ca-certificates \
        curl \
        gdb \
        git \
        openssh-client \
        ripgrep \
    && rm -rf /var/lib/apt/lists/*

USER coder

WORKDIR /workspace/ns-3