/*
 * SPDX-License-Identifier: GPL-2.0-only
 */

#include "catra-active-time-estimator.h"

#include "ns3/assert.h"
#include "ns3/simulator.h"

#include <algorithm>

namespace ns3
{
    // Invalid weights would silently create a nonsensical EWMA, while a zero
    // EP would also cause division by zero in GetRealBandwidthRatio(). Fail at
    // construction time so every later sample has well-defined semantics.

CatraActiveTimeEstimator::CatraActiveTimeEstimator(uint32_t stationIndex,
                                                   Time estimationPeriod,
                                                   double historyWeight,
                                                   ReportCallback reportCallback)
    : m_stationIndex(stationIndex),
      m_estimationPeriod(estimationPeriod),
      m_historyWeight(historyWeight),
      m_reportCallback(std::move(reportCallback))
{
    NS_ABORT_MSG_IF(estimationPeriod <= Time(0), "CATRA estimation period must be positive");
    NS_ABORT_MSG_IF(historyWeight < 0.0 || historyWeight > 1.0,
                    "CATRA history weight must be in [0, 1]");
}

void
CatraActiveTimeEstimator::Start(Time startTime)
{
    NS_ABORT_MSG_IF(m_started, "CATRA active-time estimator can only be started once");
    // All period boundaries are derived from the caller-supplied start time,
    // not from the time at which this method happens to execute. This keeps
    // samples from different stations aligned on identical EP boundaries.
    m_started = true;
    m_periodStart = startTime;
    m_periodEnd = startTime + m_estimationPeriod;
    m_stopTime = Time::Max();
    // ClosePeriod schedules all later reports, so there is only one periodic
    // event chain per station.
    Simulator::Schedule(m_periodEnd - Simulator::Now(),
                        &CatraActiveTimeEstimator::ClosePeriod,
                        this);
}

void
CatraActiveTimeEstimator::Stop(Time stopTime)
{
    // The already scheduled ClosePeriod event is left in the event queue. It
    // observes this boundary and exits cleanly, avoiding EventId ownership and
    // cancellation complexity in this small measurement component.
    m_stopTime = stopTime;
}

void
CatraActiveTimeEstimator::NotifyPhyState(Time start, Time duration, WifiPhyState state)
{
    // This stage intentionally measures only transmissions made by the local
    // radio. Other states describe time observed by the station, not airtime
    // directly generated by it. A later strict paper port will classify TCP
    // DATA/ACK transactions before deciding which complete exchanges belong
    // to the station.
    if (!m_started || state != WifiPhyState::TX || duration <= Time(0))
    {
        return;
    }
    // Count transitions independently from their duration. Comparing both
    // values in logs helps reveal a broken trace connection or implausibly long
    // individual transmissions.
    ++m_txStateEvents;
    AddTxOverlap(start, start + duration);
}

void
CatraActiveTimeEstimator::AddTxOverlap(Time start, Time end)
{
    // PHY state events normally fit inside one EP. If one crosses an EP
    // boundary, account for its first part now and deliver its remainder after
    // ClosePeriod has advanced the estimator to the next window.
    // Intersection([start, end), [periodStart, periodEnd)) prevents airtime
    // before estimator startup or after this EP from leaking into its total.
    const Time overlapStart = std::max(start, m_periodStart);
    const Time overlapEnd = std::min(end, m_periodEnd);
    if (overlapEnd > overlapStart)
    {
        m_rawTxTime += overlapEnd - overlapStart;
    }
    if (end > m_periodEnd)
    {
        // ClosePeriod was scheduled before this callback, so at this same
        // timestamp it advances the window first. The deferred call can then
        // place the remainder in the new period without double counting.
        Simulator::Schedule(m_periodEnd - Simulator::Now(),
                            &CatraActiveTimeEstimator::AddTxOverlap,
                            this,
                            m_periodEnd,
                            end);
    }
}

void
CatraActiveTimeEstimator::ClosePeriod()
{
    if (m_periodEnd > m_stopTime)
    {
        // Do not normalize a partial tail interval by a full EP. Such a sample
        // would make RBRs artificially small and could mislead later CW logic.
        return;
    }

    // Algorithm 1 applies an exponentially weighted moving average:
    //   TActive(k) = 0.8 * TActive(k-1) + 0.2 * rawTxTime(k)
    // The initial TActive is zero by construction, matching the paper.
    const double currentWeight = 1.0 - m_historyWeight;
    m_smoothedActiveTime = Seconds(m_historyWeight * m_smoothedActiveTime.GetSeconds() +
                                   currentWeight * m_rawTxTime.GetSeconds());

    // Snapshot every value before resetting the raw period counters. The
    // callback therefore sees one internally consistent completed period.
    CatraActiveTimeSample sample;
    sample.stationIndex = m_stationIndex;
    sample.periodStart = m_periodStart;
    sample.periodEnd = m_periodEnd;
    sample.rawTxTime = m_rawTxTime;
    sample.smoothedActiveTime = m_smoothedActiveTime;
    sample.realBandwidthRatio = GetRealBandwidthRatio();
    sample.txStateEvents = m_txStateEvents;
    if (m_reportCallback)
    {
        m_reportCallback(sample);
    }

    // Advance to the adjacent non-overlapping EP. TActive is deliberately kept
    // as EWMA history; only current-period raw counters are cleared.
    m_periodStart = m_periodEnd;
    m_periodEnd += m_estimationPeriod;
    m_rawTxTime = Time(0);
    m_txStateEvents = 0;
    Simulator::Schedule(m_estimationPeriod, &CatraActiveTimeEstimator::ClosePeriod, this);
}

Time
CatraActiveTimeEstimator::GetSmoothedActiveTime() const
{
    return m_smoothedActiveTime;
}

double
CatraActiveTimeEstimator::GetRealBandwidthRatio() const
{
    // Both numerator and denominator are times, so RBRs is dimensionless. A
    // value of 0.25 means smoothed local TX airtime occupies 25% of one EP.
    return m_smoothedActiveTime.GetSeconds() / m_estimationPeriod.GetSeconds();
}

} // namespace ns3
