#!/usr/bin/env python3
"""Plot any ns-3 TCP congestion-window CSV that follows the common schema."""

import argparse
import csv
import sys
from collections import defaultdict

try:
    import plotext as plt
except ModuleNotFoundError:
    print(
        "plotext is not installed. Install it with: python3 -m pip install 'plotext>=6.1'",
        file=sys.stderr,
    )
    raise SystemExit(2)


PHASE_STYLE = {
    "SLOW_START": ("Slow Start (S)", "green+", "S"),
    "CONGESTION_AVOIDANCE": ("Additive Increase (A)", "cyan+", "A"),
    "LOSS_RECOVERY": ("Multiplicative Decrease (M)", "red+", "M"),
}


def parse_args():
    parser = argparse.ArgumentParser(
        description="Draw a common ns-3 TCP congestion-window CSV using plotext."
    )
    parser.add_argument("csv_file", help="CSV generated by a TCP congestion example")
    parser.add_argument("--width", type=int, default=120)
    parser.add_argument("--height", type=int, default=35)
    return parser.parse_args()


def load_samples(csv_file):
    samples = []
    with open(csv_file, newline="", encoding="utf-8") as stream:
        for row in csv.DictReader(stream):
            samples.append(
                {
                    "time": float(row["time_s"]),
                    "cwnd": float(row["new_cwnd_mss"]),
                    "ssthresh": float(row["ssthresh_mss"]),
                    "ssthresh_bytes": int(row["ssthresh_bytes"]),
                    "phase": row["phase"],
                }
            )
    if not samples:
        raise ValueError(f"No congestion-window samples found in {csv_file}")
    return samples


def main():
    args = parse_args()
    try:
        samples = load_samples(args.csv_file)
    except (OSError, KeyError, ValueError) as error:
        print(f"Cannot plot congestion window: {error}", file=sys.stderr)
        return 1

    by_phase = defaultdict(lambda: ([], []))
    for sample in samples:
        times, windows = by_phase[sample["phase"]]
        times.append(sample["time"])
        windows.append(sample["cwnd"])

    figure = plt.figure.clear()
    figure.plot_size(args.width, args.height)
    figure.theme("dark")
    figure.title("TCP Congestion Window: cwnd, ssthresh, Slow Start and AIMD")
    figure.label("Simulation time (s)", axis=0)
    figure.label("cwnd (MSS)", axis=1)

    # UINT32_MAX means that the initial threshold is effectively unlimited. Plotting it would
    # flatten the useful cwnd range, so the threshold starts at the first finite loss response.
    finite_thresholds = [
        sample for sample in samples if sample["ssthresh_bytes"] < 2**32 - 1
    ]
    if finite_thresholds:
        threshold_times = [finite_thresholds[0]["time"]]
        threshold_values = [finite_thresholds[0]["ssthresh"]]
        previous_threshold = finite_thresholds[0]["ssthresh"]
        for sample in finite_thresholds[1:]:
            if sample["ssthresh"] != previous_threshold:
                # Repeat the old value at the change time to draw a vertical step, not a diagonal.
                threshold_times.append(sample["time"])
                threshold_values.append(previous_threshold)
                previous_threshold = sample["ssthresh"]
            threshold_times.append(sample["time"])
            threshold_values.append(previous_threshold)

        threshold_marker = plt.marker(
            "=", pixel=plt.pixel(foreground="orange+", style="bold")
        )
        threshold_signal = figure.signal(
            threshold_times,
            threshold_values,
            marker=threshold_marker,
        ).lines().label("ssthresh")
        figure.draw(threshold_signal)

    cwnd_marker = plt.marker("dot", pixel=plt.pixel(foreground="white", style="bold"))
    cwnd_signal = figure.signal(
        [sample["time"] for sample in samples],
        [sample["cwnd"] for sample in samples],
        marker=cwnd_marker,
    ).lines().label("cwnd")
    figure.draw(cwnd_signal)
    for phase, (times, windows) in by_phase.items():
        label, color, symbol = PHASE_STYLE.get(phase, (phase, "yellow", "?"))
        phase_marker = plt.marker(symbol, pixel=plt.pixel(foreground=color, style="bold"))
        figure.draw(figure.signal(times, windows, marker=phase_marker).label(label))
    figure.show()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
